name: DevOps Lab CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask psycopg2-binary

    - name: Lint with flake8
      run: |
        pip install flake8
        # Остановка сборки, если есть синтаксические ошибки
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Build Docker Image
      run: |
        docker build -t nexuscorp-app:latest ./docker/app